export const types = {
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  UI_SET_ERROR: "UI_SET_ERROR",
  UI_REMOVE_ERROR: "UI_REMOVE_ERROR",
  UI_INIT_LOADING: "UI_INIT_LOADING",
  UI_STOP_LOADING: "UI_STOP_LOADING",
};
