export const types = {
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  UI_SET_ERROR: "UI_SET_ERROR",
  UI_REMOVE_ERROR: "UI_REMOVE_ERROR",
  UI_INIT_LOADING: "UI_INIT_LOADING",
  UI_STOP_LOADING: "UI_STOP_LOADING",
  NOTES_ADD: 'NOTES_ADD',
  NOTES_ACTIVE: 'NOTES_ACTIVE',
  NOTES_LOAD: 'NOTES_LOAD',
  NOTES_UPDATE: 'NOTES_UPDATE',
  NOTES_URL_FILE: 'NOTES_URL_FILE',
  NOTES_DELETE: 'NOTES_DELETE',
  NOTES_LOGOUT: 'NOTES_LOGOUT'
};
